### ISSUE TITLE
White terminal fails

### ISSUE THREAD

**Issue by Yajo** [Unrud/remote-touchpad#1]
In my system, the terminal is configured with white background and black letters. This makes the phone not to recognize the QR code:

![captura de pantalla de 2018-08-14 13-28-42](https://user-images.githubusercontent.com/973709/44091676-272e13ec-9fc6-11e8-9b9b-221851de1610.png)

I installed through flathub.

I think the app should make sure QR is always black over white.

**Comment by Yajo** [comment]
Oh I didn't know. However I still think it's better to make it "always work" by default. In terminal programs, usually one can define the output color. Can't that be done in this app? :thinking: AFAIK, [if you manually define the output's background and foreground colors](https://askubuntu.com/a/681719/546142), those will be respected, no matter the terminal theme.

**Comment by Unrud** [comment]
I hadn't thought of that. Fixed in f2a7c1dc1d77cae67751937b06af2d453e9e2983.
