### ISSUE TITLE
Wayland support?

### ISSUE THREAD

**Issue by davidpicard** [Unrud/remote-touchpad#11]
Is there any chance to have wayland support at some point? How complicated would it be?

**Comment by Unrud** [comment]
The freedesktop.org RemoteDesktop portal is supported: https://github.com/Unrud/remote-touchpad/blob/master/backend_portal.go

I have tested it on Fedora with Gnome Wayland. Mouse support works fine but the keyboard only works partially.

**Comment by Unrud** [comment]
I will this for now.
