### ISSUE TITLE
Features request: Add mouse acceleration, touch gestures

### ISSUE THREAD

**Issue by ruathudo** [Unrud/remote-touchpad#13]
I think these are helpful features. Currently, I need to swipe few times on my phone to move the cursor to the place I want. It would be great if we could have mouse acceleration feature. 
Furthermore, if we could add some useful touch gestures for browsing (backward, forward), open overview in Linux gnome, etc, that would be awesome.

Thanks for the great work!

**Comment by Unrud** [comment]
We already have [pointer acceleration](https://github.com/Unrud/remote-touchpad/blob/fad0e2d7c021612e9bffb326432156ec25c04e22/webdata/fn.js#L24) but the parameters may require some tuning.

I'm not a big fan of gestures but we could add an additional row of shortcut buttons to the volume and playback controls.

**Comment by hiren1771** [comment]
> Thanks for the great work!

I have to agree, thanks so much for this project! Works very well. I use it on the atomic pi soc board. It runs lxde with a terminal console that does not support unicode, so the qr does not work. But that's no problem it prints the url which I put into the phone browser. I customize the key and port to make it easier and bookmark. Once again thanks a lot.
