### ISSUE TITLE
Will it support multi-finger operation?

### ISSUE THREAD

**Issue by nalido** [Unrud/remote-touchpad#21]
Finally I found such a nice project that is simple enough and clear enough! The one sadness is that it seems not support multi-finger operation? Will it support that in the feature? Wating for that feature.

**Comment by belden** [comment]
multi-finger operations are mentioned in https://github.com/Unrud/remote-touchpad/issues/31

* 2-finger tap: right-click
* 3-finger tap: middle-click

**Comment by phil0x2e** [comment]
Also scrolling with two fingers works for me

**Comment by Polisson** [comment]
The most popular (big and great) Linux desktop environments have multi finger gestures like switching desktops, invoking overview or desktops grid. Would be nice to use them, not only translate to trivial keyboard and mouse actions.

**Comment by Unrud** [comment]
Not planned.
