### ISSUE TITLE
Keyboard send every keystroke one by one.

### ISSUE THREAD

**Issue by toger5** [Unrud/remote-touchpad#26]
Typing and than sending the whole string makes it super hard to edit text typed on the remote computer. 
Especially deleting and correcting single characters is almost impossible.

An option would be nice to immediately send every keystroke.

**Comment by Naheel-Azawy** [comment]
Hello,
I totally agree this would be great.
I don't have anything solid yet but you can check this video.

https://user-images.githubusercontent.com/5764614/149682226-a1929f3e-1b0d-4e57-beb2-38ce77e6fb2f.mp4

As of now, only few keycodes are mapped and I'm only considering my physical keyboard layout.
All what I did is adding the following to `fn.js`:
```js
    window.onkeyup = function(e) {
        ws.send("c" + e.keyCode);
        return true;
    };
```
And then handling 'c' in `main.go`. The mapping is also done manually.

**Comment by Unrud** [comment]
Added more keys (arrow keys, backspace, delete and return): d22dc0f4dd58a9a6fdb38bc4c75e42e73613d17d, 5da7b376c93d3c35eb7b9e5199541a7b6e6963bc
Support for physical keyboard: 3014af960b762e74abd6a89551e19147e03d6413

**Comment by Naheel-Azawy** [comment]
Very nice. Thank you @Unrud

**Comment by toger5** [comment]
Thanks a lot 😍
