### ISSUE TITLE
ios: Confusing zooming on fast touch

### ISSUE THREAD

**Issue by mrkeuz** [Unrud/remote-touchpad#28]
HI @Unrud

Many thanks for great tool!
I faced with next behavior, when you try to volume up/down with many touches quite fast, browser view make zoom in and buttons just move from their position, so you're making miss touch.

I found solution:
https://stackoverflow.com/questions/46167604/ios-html-disable-double-tap-to-zoom
https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action

Interesting note this happened only on buttons. For other screen and touchpad it is not zoomed.
I'm not frontend/CSS developer, so maybe there is some better solution for this.

I can prepare PR and make tests. What do you think about this?

**Comment by alkemyst** [comment]
Hi @mrkeuz ,
  I am by no means the author of this package. I think I proposed a patch at a point (kind of remember it).
  You should contact the main developers.

Cheers
Stefano

**Comment by mrkeuz** [comment]
@alkemyst sorry, some typo in mention by some reason. Never mind I will edit original propose.

**Comment by mrkeuz** [comment]
Thanks! 🚀
