### ISSUE TITLE
Please add mouse buttons.

### ISSUE THREAD

**Issue by KyleDave** [Unrud/remote-touchpad#31]
I was hoping to use this to draw or write on my PC with a little more ease than a mouse, but it's not possible without mouse buttons.

**Comment by Unrud** [comment]
> Like in my case where I want to right-click to open a link in a new browser tab.

You can right and middle click by tapping with 2 or 3 fingers.

**Comment by catnapster** [comment]
Oh wow, this just got even better

It works, it really works

**Comment by ablakely** [comment]
What about for like dragging a window or selecting text?
