### ISSUE TITLE
[Question] Command argument ready to use [Ubuntu]

### ISSUE THREAD

**Issue by rodrigoverasantis** [Unrud/remote-touchpad#32]
Hello, is there any command argument to start the program ready to use?
I would like to start Ubuntu, run a command on startup, and a show a console ready with the QR code.
Sadly, first I have to select 1 of the options (mouse, keyboard, touch screen) before show the QR code.

**Comment by Unrud** [comment]
The [Remote Desktop Portal](https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-org.freedesktop.portal.RemoteDesktop) is used to control keyboard and mouse. I don't think it's possible to automatically grant permissions without user input.

**Comment by evedark1** [comment]
Is this possible using <linux/input.h> simulate user input? It will work without X11.
As for QR code, fixed URL can be used in this situation.
I find a example: https://github.com/evuraan/edotool

**Comment by Unrud** [comment]
@evedark1 [uinput](https://www.kernel.org/doc/html/latest/input/uinput.html) is supported. You need to compile with `-tags uinput` and set permissions on `/dev/uinput`.
