### ISSUE TITLE
Cant start without login manager

### ISSUE THREAD

**Issue by L3SP1NK** [Unrud/remote-touchpad#33]
When X is launched with "startx" or "xinit" I have the following error message:

"X11 backend: unsupported session type 'tty'
RemoteDesktop portal backend: keyboard or pointer source type not supported
Windows backend: disabled"

So I had to install a login manager (lightdm) to launch te app, and everything work perfectly.
I wonder if there is a way to launch it without a login manager ?

**Comment by Unrud** [comment]
You have to set the environment variable `XDG_SESSION_TYPE=x11`.

**Comment by L3SP1NK** [comment]
Thanks, it worked ! 😉
