### ISSUE TITLE
X11 backend: unsupported session type 'wayland'

### ISSUE THREAD

**Issue by trungus** [Unrud/remote-touchpad#34]
Hi guys,

I have this error when I trying to use RemoteTouch in wayland session

```
2021/10/08 21:10:37 unsupported platform:
X11 backend: unsupported session type 'wayland'
RemoteDesktop portal backend: keyboard or pointer source type not supported
Windows backend: disabled
```
I am using Nitrux OS 1.6.1 with wayland.

Some ideas?

**Comment by Unrud** [comment]
On Wayland the [Remote Desktop Portal](https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-org.freedesktop.portal.RemoteDesktop) is used to control keyboard and mouse.
```
RemoteDesktop portal backend: keyboard or pointer source type not supported
```
The error message means that [AvailableDeviceTypes](https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-property-org-freedesktop-portal-RemoteDesktop.AvailableDeviceTypes) does not have the bits for `KEYBOARD` or `POINTER` set.
