### ISSUE TITLE
problem when using a vpn

### ISSUE THREAD

**Issue by ghistes** [Unrud/remote-touchpad#35]
Hi,

remote-touchpad as such works great on my system (as flatpak on Debian testing).

However there is one annoyance:

When my system is connected to a vpn (via openvpn) and I start remote-touchpad, the webserver uses the ip of the tun-device that openvpn creates, rather than the address in the local network - and then my mobile cannot connect.

So in this particular case it seems FindDefaultHost determines the wrong ip-address.

Starting remote-touchpad before connecting to a vpn works.

**Comment by Unrud** [comment]
You can manually specify the address with the `-bind` argument.
