### ISSUE TITLE
Static QR Code

### ISSUE THREAD

**Issue by jellz77** [Unrud/remote-touchpad#38]
I would like to have the QR code be static and not change every time on start up.  THis program is amazing!!! :)

**Comment by Unrud** [comment]
The QR code changes because the TCP port and secret are random. You can fix them with the `-bind` and `-secret` argument.
(e.g. `flatpak run com.github.unrud.RemoteTouchpad -bind :46507 -secret 6u1PoTlPh+E=`)

**Comment by jellz77** [comment]
Thank you!!!!! Life saver :)
