### ISSUE TITLE
feature: sensitivity controls

### ISSUE THREAD

**Issue by tiagogaspar8** [Unrud/remote-touchpad#41]
Hi,

Are there any plans to add sensitivity controls?

Thanks!

**Comment by Unrud** [comment]
Added command line options in 98f4d1c6924dfabce801ce6ceb4c461d72b77563

**Comment by tiagogaspar8** [comment]
Hi @Unrud 

Is there some documentation on all the available command line options?

Thanks.

**Comment by mrkeuz** [comment]
@tiagogaspar8, try `remote-touchpad --help`
