### ISSUE TITLE
When trying to type in greek (probably other languages too) letters are typed with a delay

### ISSUE THREAD

**Issue by Twilight0** [Unrud/remote-touchpad#46]
I am using Linux Mint 20 (Ubuntu 20.04)

When trying to type text in greek characters they are typed once every 500 ms or so, when latin characters are to be typed, they are typed instantly.

Tried both being in VPN connection and not.

**Comment by Unrud** [comment]
It's a limitation of the X11 controller:

https://github.com/Unrud/remote-touchpad/blob/1675d5d2f8b54026121fec27158fce5950d1d1ef/inputcontrol/controller_x11.go#L211-L224

https://github.com/Unrud/remote-touchpad/blob/1675d5d2f8b54026121fec27158fce5950d1d1ef/inputcontrol/controller_x11.go#L235-L238

If the keysym that should be typed is not already mapped to a keycode, it gets mapped to an empty keycode. Unfortunately, propagation of the new keyboard mapping to X clients is prone to race conditions and we wait 500ms for safety.

I don't have a solution for this. If it's supported by your system, you could use the portal controller ([xdg-desktop-portal](https://flatpak.github.io/xdg-desktop-portal/)), it doesn't suffer from the problem.

**Comment by Twilight0** [comment]
For some reason yesterday I briefly hadn't been experiencing the issue and that puzzles me even more.

**Comment by robartsd** [comment]
> It's a limitation of the X11 controller:
> 
> https://github.com/Unrud/remote-touchpad/blob/1675d5d2f8b54026121fec27158fce5950d1d1ef/inputcontrol/controller_x11.go#L211-L224
> 
> https://github.com/Unrud/remote-touchpad/blob/1675d5d2f8b54026121fec27158fce5950d1d1ef/inputcontrol/controller_x11.go#L235-L238
> 
> If the keysym that should be typed is not already mapped to a keycode, it gets mapped to an empty keycode. Unfortunately, changing the keyboard mapping is prone to race conditions and we wait 500ms for safety.
> 
> I don't have a solution for this. If it's supported by your system, you could use Wayland. It doesn't suffer from the problem.

Perhaps a command line option to adjust the delay length would allow the user to tune to what works on their system.

**Comment by Unrud** [comment]
No changes planned. In the future we can prefer the remote desktop portal even when using X11. Maybe that will mitigate the problem.
