### ISSUE TITLE
No response on my phone browser

### ISSUE THREAD

**Issue by willsionggg** [Unrud/remote-touchpad#48]
Hi I get no response on my browser when I paste the URL tried many times I'm on the same network

**Comment by Moooartin** [comment]
Hi,
If you are using it from Linux, verify if the firewall (should be ufw) is enabled. Then if it is, allow the port currently use by remote-touchpad.
I haven't been looking at the code, but I reckon it uses a port range which could be defined on the firewall.

**Comment by mickleberry** [comment]
Yeh it took me a while to realise i had to adjust the ufw firewall... 
Then i'd find it still wasn't working, and the problem would be i was still on roaming/4G and hadn't joined the local wifi yet. 
(Hope this person found a solution)

Great app btw, really appreciating it 😸

**Comment by Unrud** [comment]
By default it uses some free port. The port can be set with the `-bind` argument.
