### ISSUE TITLE
Not working for iOS 16?

### ISSUE THREAD

**Issue by joshcho** [Unrud/remote-touchpad#49]
On 16.0.3, with Arch Linux and X11.

**Comment by ams1** [comment]
I've just tested the webapp on ios 16.3.1 and the touchpad works flawlessly - imo this can be closed.

P.S.: 
@Unrud - this is an awesome initiative!
```go
package main; import "fmt"; func main() { for i := 0; i < 1000; i++ { fmt.Println("Thank you!") } }
```
