### ISSUE TITLE
Adding volume control to UI

### ISSUE THREAD

**Issue by AdamKane41** [Unrud/remote-touchpad#5]
Hey.
How easy would it be to add **Volume_Up** and **Volume_Down** functions  at the bottom of the UI? Maybe using the MultiMedia functions keys or **XF86AudioRaiseVolume**  & **XF86AudioLowerVolume** in order to control the host/server device's Master Volume level. 
I created this mock-up:
![screenshot_2018-09-23-01-15-50](https://user-images.githubusercontent.com/30092603/45925368-b184f580-bee1-11e8-98d8-632cb1ffb84b.png)

Peace!

**Comment by Unrud** [comment]
![](https://raw.githubusercontent.com/Unrud/remote-touchpad/master/screenshots/2.png)

Done.

**Comment by AdamKane41** [comment]
Niiiiiice! Any way to build or is it flatpak only? flatpak is still at "old" version at the moment ...
peace
