### ISSUE TITLE
Requesting native package: Atrocious 2.7 GB Flatpak!

### ISSUE THREAD

**Issue by a-p-jo** [Unrud/remote-touchpad#50]
I'm very grateful for this app because it is orders of magnitude more responsive and better feeling that KDE Connect's "Remote Input". Scrolling works well, and there is almost no lag. 

The one issue is the bloat that arises due to this being packaged as a Flatpak or Snap only. On Linux Mint 21.1 XFCE, when I install the flatpak it requires 2.7 GB space which is absurd! Further, being packaged like this means it will use more RAM than it otherwise would have which is a big deal for older systems with less memory.

The project seems to be written in Go and have no GUI, which should make it trivial to package as a .deb and perhaps an .rpm. I'm sure you understand that 2.7 GB is most unreasonable!

**Comment by Unrud** [comment]
I'm not interested in offering other packages, but feel free to package it yourself.

You can always install it directly with Go:

```
go install -tags portal,uinput,x11 github.com/unrud/remote-touchpad@latest
```

> Atrocious 2.7 GB Flatpak! 

The runtime is ~520 MiB and the package itself is ~6 MiB. (Flatpak creates multiple hardlinks to the same files. You need to take that this into account when calculating the disk space.)

> Further, being packaged like this means it will use more RAM than it otherwise would have which is a big deal for older systems with less memory.

There should be no significant impact on RAM usage.
