### ISSUE TITLE
CMakeLists.txt is missing

### ISSUE THREAD

**Issue by athmanenaciri** [Unrud/remote-touchpad#53]
Title: Issue with CMakeLists.txt file in remote-touchpad repository

Description:
I am attempting to build the remote-touchpad software on my Manjaro Linux system, but I am encountering an error related to the CMakeLists.txt file. When I run the cmake command in the remote-touchpad directory, I receive the following error message:
" CMake Error: The source directory "/home/myuser/Desktop/remote-touchpad" does not appear to contain CMakeLists.txt."
However, when I navigate to the remote-touchpad directory, I cannot find the CMakeLists.txt file.

Steps to reproduce:
1. Download the remote-touchpad source code from the GitHub repository (https://github.com/Unrud/remote-touchpad.git)
2. Navigate to the remote-touchpad directory and run the cmake command: "cmake ."
3. Receive the error message: "CMake Error: The source directory "/home/myuser/Desktop/remote-touchpad" does not appear to contain CMakeLists.txt."
4. Navigate to the remote-touchpad directory and check for the presence of CMakeLists.txt.

Expected result:
The cmake command should be able to find the CMakeLists.txt file in the remote-touchpad directory and build the software successfully.

Actual result:
The CMakeLists.txt file is missing from the remote-touchpad directory, causing the cmake command to fail.

Additional information:
- My Linux distribution is Manjaro Linux 22.0.5.
- I have tried downloading the source code again from the GitHub repository, but the CMakeLists.txt file is still missing.
- I have synced my package manager and attempted to install the remote-touchpad package, but it is not found.

Please let me know if there is any additional information I can provide to help resolve this issue. Thank you.

**Comment by Unrud** [comment]
The project does not use **cmake**, so there is no **CMakeLists.txt**. You can compile it with **go**.
