### ISSUE TITLE
Please add the option to reverse the scrolling

### ISSUE THREAD

**Issue by kasra-trendplus** [Unrud/remote-touchpad#55]
Actually the scrolling is natural scrolling.
I want it to be reverse. meaning that when I move two fingers up the scrollbar should go up also.

Please add a command line argument supporting this. Thanks.

**Comment by Unrud** [comment]
Use argument `-scroll-speed -1`

**Comment by kasra-trendplus** [comment]
Is this a new argument? I did not saw this even in the source code.
Anyway thanks for your time. I actually ended up cloning and editing the source code myself! but it would be good addition to reverse both horizontal and vertical axis moves.

**Comment by kasra-trendplus** [comment]
Is this a new argument? I did not saw this even in the source code.
Anyway thanks for your time. I actually ended up cloning and editing the source code myself! but it would be good addition to reverse both horizontal and vertical axis moves.

**Comment by Unrud** [comment]
Yes, it's an argument.
