### ISSUE TITLE
Stuck at connecting screen

### ISSUE THREAD

**Issue by ZhangTianrong** [Unrud/remote-touchpad#61]
I have been using `remote-touchpad` without a problem for quite some years until recently when I am stuck at the connecting screen. The following are the error in the web console and nothing else
```
Loading module from “http://192.168.1.107:9501/app/main.mjs” was blocked because of a disallowed MIME type (“text/plain”).
``` 
Reverting to earlier versions seems to have solved the problem. Upon testing `1.3.0` is the latest build that is working.

**Comment by Unrud** [comment]
It returns the correct mime-type for me: `Content-Type: text/javascript; charset=utf-8`
I guess the mime type for **mjs** was missing in an older version of the Golang network library.

I am closing this issue for now. If the problem still occurs, you can open it again.
