### ISSUE TITLE
Ubuntu 23.10, stopped working after update

### ISSUE THREAD

**Issue by Siete-exe** [Unrud/remote-touchpad#63]
After updating to Ubuntu 23.10, remote-touchpad stopped asking for permission to access remote desktop. It was installed from ubuntu store (snap).

I tried reinstalling the snap, but still the same.

**Comment by ddcech** [comment]
For me i am able to visit the web page and I see the interface, but the mouse does not move

**Comment by Unrud** [comment]
Unfortunately the Xwayland detection broke with a new X server release.

**Comment by Siete-exe** [comment]
Last version (latest/edge 1.4.6) it's working in Ubuntu 24.04, thank you
