### ISSUE TITLE
Android Support Neglected

### ISSUE THREAD

**Issue by otboss** [Unrud/remote-touchpad#64]
Support for this software on Android Linux (via Termux) is non-existent. See the screenshot below:

![image](https://github.com/Unrud/remote-touchpad/assets/24215073/a8c445e9-c7cb-44b9-80c3-1285f1f46070)

## Why? 
I was planning to carry only my android phone and work laptop to my workplace and be able to control my phone via remote-touchpad using the laptop's keyboard and touchpad and do some Linux shell work on my Android phone. Unfortunately ADB has been blocked on my work laptop so I can't use that. Remote-Touchpad could have been a nice web-based work around if only it worked.

Android is one of the most popular operating systems yet it gets no love

**Comment by Unrud** [comment]
Android support is not planned. It would require a separate android app that implements an [AccessibilityService](https://developer.android.com/reference/android/accessibilityservice/AccessibilityService) and draws a "virtual" mouse pointer on the screen.
