### ISSUE TITLE
Remote Desktop Portal support broken

### ISSUE THREAD

**Issue by spersson** [Unrud/remote-touchpad#67]
When using xdg-desktop-portal-kde the call to SelectDevices fails.

Checking [the documentation](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.RemoteDesktop.html)  I see that the vardict key should be "types", not "type". Changing that on line 112 of `controller_portal.go` makes it work.

I can't find any older version of the portal documentation so I don't know if this key name has changed or if it's always been like that and that just some backends are strict in not allowing unsupported options in the dictionary.

**Comment by Unrud** [comment]
Thank you, I think it was always broken.
