### ISSUE TITLE
In full screen mode, on vol/media page, browser's back button breaks fullscreen

### ISSUE THREAD

**Issue by AdamKane41** [Unrud/remote-touchpad#7]
1-Main window (touchpad)
2-click Full screen (lower left icon)
3-click new volume/media control icon (top)
4-new page opens in full screen mode with all vol/media icons
5- return to main touchpad page (using browser's back button)
6- main window shows up but in webpage mode (no longer fullscreen)

peace

**Comment by AdamKane41** [comment]
does the same with text input screen... when backing to main , full screen is lost

**Comment by Unrud** [comment]
> does the same with text input screen... when backing to main , full screen is lost

The on-screen keyboard can behave strangely in full screen mode, therefore It's exited when showing the keyboard.

Unfortunately it's not possible to automatically go back to full screen, when returning to the pad.

> How about:

The multimedia keys now behave like the keyboard, I don't want to add  an extra button.
