### ISSUE TITLE
Tls

### ISSUE THREAD

**Issue by Waspoedertje** [Unrud/remote-touchpad#74]
How can i make  the windows exe https ?

**Comment by bigstusexy** [comment]
The program has command switches. You'll need to first create (or just have available) a certificate and a private key, then run the program  and specify certificate and key file with these -cert {certificate file} -key {private key file}

**Comment by Waspoedertje** [comment]
Thanks it rund now
To bad home assistant ios app doesn’t like the selfsigned  certificate but it opens in safari now

thanks
