### ISSUE TITLE
Not working on iOS (I guess)

### ISSUE THREAD

**Issue by dewi-g** [Unrud/remote-touchpad#8]
Hi, the program is not working when I'm connecting from Fedora 30 (GNOME on Xorg) to my iPhone 7 and the page just shows disconnected. Not a problem to me but I thought you might want to know ;)

**Comment by Unrud** [comment]
I don't have access to an iPhone. Maybe TLS is required.

**Comment by imReker** [comment]
Works for me on 12.4 iPhone XR + Windows 10

**Comment by dewi-g** [comment]
I have Fedora 31 and iPhone 7

> I don't have access to an iPhone. Maybe TLS is required.

and also how do I  or like, what it means that TLS is required? I ****

**Comment by dewi-g** [comment]
I have Fedora 31 and iPhone 7.

Also what do you mean by TLS is required, I checked apple support page and it says that TLS is enabled automatically from some version above, and since I have the latest os version and my phone is still supported, I very probably do have the required version.

**Comment by dewi-g** [comment]
Sorry I'm an idiot, didn't use x11 but wayland instead
