### ISSUE TITLE
Can't input chinese input Method on Keyboard screen

### ISSUE THREAD

**Issue by f914095** [Unrud/remote-touchpad#9]
I changed to Keyboard Screen, changed chinese input Method  but unable sucess Input to Textbox

**Comment by Unrud** [comment]
Are you using Microsoft Windows?

**Comment by f914095** [comment]
> Are you using Microsoft Windows?

server is Ubuntu 18.04.3, Client is Iphone 6s

I'm user web brower Linked url  that click keyboard icon to input text(any chinese   word  ) .It's Unable  Display On  Textbox to send

**Comment by Unrud** [comment]
Do you get any error messages on the server?

I've tested it with Android 9 and Ubuntu 18.04. Inputting and sending chinese words works.

**Comment by f914095** [comment]
> Do you get any error messages on the server?
> 
> I've tested it with Android 9 and Ubuntu 18.04. Inputting and sending chinese words works.

**Comment by f914095** [comment]
please look at video https://youtu.be/OuuThuAnzZs

**Comment by Unrud** [comment]
> please look at video

The video is private. I can't access it.

**Comment by f914095** [comment]
> > please look at video
> 
> The video is private. I can't access it.
The video is changed to public

**Comment by Unrud** [comment]
Can you test if the problem still exists in the new version (0.0.16)?

**Comment by f914095** [comment]
> Can you test if the problem still exists in the new version (0.0.16)?

I'm tested is ok,but print  Text  speed  is low  on PC

**Comment by Unrud** [comment]
> I'm tested is ok,but print Text speed is low on PC

That's a problem with X11. When a character is not already mapped to Keycode we have to map it to a free Keycode first and free it again afterwards.
Unfortunately there is a race condition between mapping the character, typing the character and un-mapping it again. I had to add a delay to deal with it: https://github.com/Unrud/remote-touchpad/blob/bd376578d4631217588b2d275cfdf8831987132b/backend_x11.go#L40
